### ISSUE TITLE
ReferenceError: path is not defined

### ISSUE THREAD

**Issue by nwork** [MCStreetguy/atom-snippet-injector#13]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Debian GNU/Linux
**Thrown From**: [snippet-injector](https://github.com/MCStreetguy/atom-snippet-injector) package 1.1.10

### Stack Trace

Failed to activate the snippet-injector package

```
At path is not defined

ReferenceError: path is not defined
    at Storage.retrieveFiles (/packages/snippet-injector/lib/storage.js:93:33)
    at Storage.migrate (/packages/snippet-injector/lib/storage.js:160:24)
    at Object.activate (/packages/snippet-injector/lib/snippet-injector.js:39:18)
    at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app/src/package.js:253:25)
    at /usr/share/atom/resources/app/src/package.js:225:38
    at Package.module.exports.Package.measure (/usr/share/atom/resources/app/src/package.js:99:21)
    at /usr/share/atom/resources/app/src/package.js:218:32
    at Package.module.exports.Package.activate (/usr/share/atom/resources/app/src/package.js:215:40)
    at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom/resources/app/src/package-manager.js:645:40)
    at /usr/share/atom/resources/app/src/package-manager.js:626:35
    at Config.module.exports.Config.transactAsync (/usr/share/atom/resources/app/src/config.js:346:24)
    at PackageManager.module.exports.PackageManager.activatePackages (/usr/share/atom/resources/app/src/package-manager.js:621:25)
    at PackageManager.module.exports.PackageManager.activate (/usr/share/atom/resources/app/src/package-manager.js:603:52)
    at /usr/share/atom/resources/app/src/atom-environment.js:846:34
```

### Commands

```
```

### Non-Core Packages

```
ascii-hex 0.2.0 
atom-beautify 0.30.4 
atom-scripts 0.1.3 
dec-hex-oct-bin 0.1.1 
gedit-oblivion 0.13.0 
hex-editor 0.1.1 
jQuery 1.2.5 
jquery-snippets 11.0.0 
markdown-writer 2.6.5 
minimap 4.29.2 
search-github 0.3.0 
snippet-injector 1.1.10 
snippets-editor 1.0.0 
sonarlint 1.0.2 
terminal-syntax 0.1.0 
toggle-markdown-task-with-ongoing 0.0.6 
```

**Comment by MCStreetguy** [comment]
I have to apologize for those bugs. For me the package worked fine, I should start testing it on Debian too.
But nevertheless I'll release a fix for that in a couple of minutes. Thanks for reporting again I hope you don't got any more issues upcoming.
