### ISSUE TITLE
Uncaught TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by MCStreetguy** [MCStreetguy/atom-snippet-injector#15]
[Enter steps to reproduce:]

1. Open import prompt
2. Cancel

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: SAMSUNG-RF711
**Thrown From**: [snippet-injector](https://github.com/MCStreetguy/atom-snippet-injector) package 1.2.5

### Stack Trace

Uncaught TypeError: Cannot read property '0' of undefined

```
At C:\Users\MCStreetguy\Documents\PROJECTS\Atom Workspace\snippet-injector\lib\imex.js:64

TypeError: Cannot read property '0' of undefined
    at ~/Documents/PROJECTS/Atom Workspace/snippet-injector/lib/imex.js:64:31
    at CallbacksRegistry.apply (~/AppData/Local/atom/app-1.18.0/resources/electron.asar/common/api/callbacks-registry.js:48:25)
    at EventEmitter.<anonymous> (~/AppData/Local/atom/app-1.18.0/resources/electron.asar/renderer/api/remote.js:282:21)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -4:57.9.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always)
     -0:25.6.0 snippet-injector:import (input.hidden-input)
```

### Non-Core Packages

```
autoclose-html 0.23.0 
emmet 2.4.3 
file-icons 2.1.9 
minimap 4.29.0 
snippet-injector 1.2.5 
sort-lines 0.14.0 
```

**Comment by MCStreetguy** [comment]
This has been fixed in release v1.2.6.
