### ISSUE TITLE
TypeError: Cannot read property 'dismissable' of null

### ISSUE THREAD

**Issue by justin-barca** [MCStreetguy/atom-snippet-injector#18]
#### Description
**What wanted you to do? what went wrong?**
I saw this was closed in a commit but I'm still having this error:
Upon inject command, and error:
/usr/share/atom/resources/app/src/notification.js:96
Hide Stack Trace
TypeError: Cannot read property 'dismissable' of null
    at Notification.isDismissable (/usr/share/atom/resources/app/src/notification.js:96:32)
    at new Notification (/usr/share/atom/resources/app/src/notification.js:14:20)
    at NotificationManager.addWarning (/usr/share/atom/resources/app/src/notification-manager.js:115:39)
    at Object.insert (/home/justin.barca/.atom/packages/snippet-injector/lib/snippet-injector.js:275:26)
    at HTMLElement.snippetInjectorInsert (/home/justin.barca/.atom/packages/snippet-injector/lib/snippet-injector.js:107:48)
    at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:388:36)
    at Object.didConfirmSelection (/usr/share/atom/resources/app/node_modules/command-palette/lib/command-palette-view.js:143:35)
    at SelectListView.confirmSelection (/usr/share/atom/resources/app/node_modules/command-palette/node_modules/atom-select-list/src/select-list-view.js:327:26)
    at HTMLDivElement.core:confirm (/usr/share/atom/resources/app/node_modules/command-palette/node_modules/atom-select-list/src/select-list-view.js:84:20)
    at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:388:36)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.handleDocumentKeyEvent (/usr/share/atom/resources/app/src/window-event-handler.js:108:40)
#### Steps to reproduce
1. run 'snippet-injector:insert' through panel

#### Environment
Atom Version: v1.23.1

##### Other installed packages:
Built-in Atom Packages (92)
├── atom-dark-syntax@0.28.0
├── atom-dark-ui@0.53.0
├── atom-light-syntax@0.29.0
├── atom-light-ui@0.46.0
├── base16-tomorrow-dark-theme@1.5.0
├── base16-tomorrow-light-theme@1.5.0
├── one-dark-ui@1.10.8
├── one-light-ui@1.10.8
├── one-dark-syntax@1.8.0
├── one-light-syntax@1.8.0
├── solarized-dark-syntax@1.1.2
├── solarized-light-syntax@1.1.2
├── about@1.7.8
├── archive-view@0.64.1
├── autocomplete-atom-api@0.10.5
├── autocomplete-css@0.17.4 (disabled)
├── autocomplete-html@0.8.3 (disabled)
├── autocomplete-plus@2.38.0
├── autocomplete-snippets@1.11.2 (disabled)
├── autoflow@0.29.0
├── autosave@0.24.6
├── background-tips@0.27.1
├── bookmarks@0.44.4
├── bracket-matcher@0.88.0
├── command-palette@0.42.0
├── dalek@0.2.1
├── deprecation-cop@0.56.9
├── dev-live-reload@0.47.1
├── encoding-selector@0.23.7
├── exception-reporting@0.42.0
├── find-and-replace@0.215.0
├── fuzzy-finder@1.7.3
├── github@0.8.3
├── git-diff@1.3.6
├── go-to-line@0.32.1
├── grammar-selector@0.49.8
├── image-view@0.62.4
├── incompatible-packages@0.27.3
├── keybinding-resolver@0.38.1
├── line-ending-selector@0.7.4
├── link@0.31.3
├── markdown-preview@0.159.18
├── metrics@1.2.6
├── notifications@0.69.2
├── open-on-github@1.3.1
├── package-generator@1.1.1
├── settings-view@0.253.0
├── snippets@1.1.9
├── spell-check@0.72.3
├── status-bar@1.8.14
├── styleguide@0.49.8
├── symbols-view@0.118.1
├── tabs@0.109.1
├── timecop@0.36.0
├── tree-view@0.221.3
├── update-package-dependencies@0.12.0
├── welcome@0.36.6
├── whitespace@0.37.5
├── wrap-guide@0.40.2
├── language-c@0.58.1
├── language-clojure@0.22.4
├── language-coffee-script@0.49.3
├── language-csharp@0.14.3
├── language-css@0.42.7
├── language-gfm@0.90.2
├── language-git@0.19.1
├── language-go@0.44.3
├── language-html@0.48.4
├── language-hyperlink@0.16.3
├── language-java@0.27.6
├── language-javascript@0.127.6
├── language-json@0.19.1
├── language-less@0.33.0
├── language-make@0.22.3
├── language-mustache@0.14.4
├── language-objective-c@0.15.1
├── language-perl@0.38.1
├── language-php@0.42.2
├── language-property-list@0.9.1
├── language-python@0.45.5
├── language-ruby@0.71.4
├── language-ruby-on-rails@0.25.2
├── language-sass@0.61.1
├── language-shellscript@0.25.4
├── language-source@0.9.0
├── language-sql@0.25.8
├── language-text@0.7.3
├── language-todo@0.29.3
├── language-toml@0.18.1
├── language-typescript@0.2.2
├── language-xml@0.35.2
└── language-yaml@0.31.1

Community Packages (77) /home/justin.barca/.atom/packages
├── atom-css-unit-converter@1.1.1
├── atom-ide-ui@0.11.2
├── atom-import-js@0.15.0
├── atom-import-sort@4.2.0
├── atom-monokai@0.10.9
├── atom-monokai-dark@0.4.0
├── atom-quokka@1.0.73
├── atom-terminal-panel@4.4.4 (disabled)
├── atom-ternjs@0.18.3
├── autocomplete@0.47.0
├── bottom-dock@0.4.4
├── busy-signal@1.4.3
├── change-case@0.6.5
├── city-lights-ui@1.3.3
├── color-picker@2.3.0
├── css-hyperclick@0.1.5
├── docblockr@0.13.7
├── emmet@2.4.3
├── es6-javascript@1.0.0
├── expand-region@0.4.0 (disabled)
├── expand-selection-to-quotes@0.11.0
├── extract-selection@0.4.0
├── file-type-icons@1.3.4
├── fix-indent-on-paste@0.1.1
├── formatter-json@1.0.1
├── from-and-to-json@1.0.0
├── git-difftool@0.2.7
├── gitlab@0.1.3-7
├── gitlab-integration@0.4.7
├── goto-definition@1.3.4
├── highlight-selected@0.13.1
├── hyperclick@0.1.5
├── ide-css@0.3.0
├── ide-html@0.4.2
├── ide-json@0.2.1
├── ide-typescript@0.7.6
├── intentions@1.1.5
├── js-hyperclick@1.13.0 (disabled)
├── jump-to-import@3.6.5 (disabled)
├── language-babel@2.85.0
├── language-javascript-plus@1.9.3
├── language-vue@0.23.1
├── language-vue-component@0.5.0
├── linter@2.2.0 (disabled)
├── linter-coffeelint@2.0.0
├── linter-eslint@8.4.1
├── linter-flake8@2.3.0
├── linter-jshint@3.1.8
├── linter-json-lint@0.1.3
├── linter-ui-default@1.7.1
├── minimap@4.29.8
├── minimap-highlight-selected@4.6.1
├── minimap-linter@2.1.3
├── monokai-dark@1.5.0
├── monokai-seti@0.9.0
├── monokai-shade@0.4.0
├── monokai-slate@0.6.0
├── numix-ui@0.2.3
├── organize-imports@1.0.0
├── pigments@0.40.2
├── platformio-ide-terminal@2.8.1 (disabled)
├── prettier-atom@0.53.0
├── pretty-json@2.0.0
├── project-manager@3.3.5
├── seti-ui@1.10.0
├── snippet-injector@1.5.3
├── sorter@1.1.0
├── sublime-block-comment@0.5.1
├── swap-selection@0.4.0
├── text-pastry@0.6.1
├── todo-show@2.3.0
├── toggle@0.6.2
├── toggle-quotes@1.1.0
├── uuidgen@1.2.1
├── vue2-autocomplete@0.1.0-alpha.4 (disabled)
├── vuejs2-snippets@1.1.0
└── xml-formatter@0.11.0

**Comment by MCStreetguy** [comment]
I'll have a closer look on this later. But on first sight it seems that something changed in the notification api.
So this will probably not be too hard to fix.

**Comment by justin-barca** [comment]
👍 Thanks

**Comment by MCStreetguy** [comment]
Actually I can't reproduce your problem. For me injecting snippets just works fine and all notifications pop up as expected. Could you update to the latest version (v1.29.0) and have a look if that fixes the error?
