### ISSUE TITLE
Failed to load the snippet-injector package

### ISSUE THREAD

**Issue by kereborn** [MCStreetguy/atom-snippet-injector#21]
I installed snippet-injector via the install package manager from atom itself, but it installed 1.5.3, which throws the "FIX: Cannot read property dismissable of null" error. So I manually installed it from your github account ( 1.5.4 ) and installed it using 'apm link'. It then gave the 'cannot find module cson', so I installed that package also, but alas, to no avail. 
Your snippet-injector seems very nice, so I really hope to be able to use it! Thank you for your efforts!

**Atom**: 1.33.1 x64
**Electron**: 2.0.16
**OS**: Ubuntu 18.04.1
**Thrown From**: [snippet-injector](https://github.com/MCStreetguy/atom-snippet-injector) package 1.5.4

### Stack Trace

Failed to load the snippet-injector package

```
At Cannot find module 'cson'

Error: Cannot find module 'cson'
    at Module._resolveFilename (module.js:543:15)
    at Module._resolveFilename (/usr/share/atom/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/usr/share/atom/resources/app/static/<embedded>:11:154667)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (/usr/share/atom/resources/app/static/<embedded>:11:145974)
    at /packages/snippet-injector/lib/sync.js:12:12)
    at /packages/snippet-injector/lib/sync.js:90:3)
    at Module.get_Module._compile (/usr/share/atom/resources/app/static/<embedded>:11:146684)
    at Object.value [as .js] (/usr/share/atom/resources/app/static/<embedded>:11:150231)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/usr/share/atom/resources/app/static/<embedded>:11:145974)
    at Object.<anonymous> (/home/koen/Projects/development/atom/atom-snippet-injector/lib/storage.js:4:32)
    at Object.<anonymous> (/home/koen/Projects/development/atom/atom-snippet-injector/lib/storage.js:13:38)
    at Module.get_Module._compile (/usr/share/atom/resources/app/static/<embedded>:11:146684)
    at Object.value [as .js] (/usr/share/atom/resources/app/static/<embedded>:11:150231)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/usr/share/atom/resources/app/static/<embedded>:11:145974)
    at /packages/snippet-injector/lib/snippet.js:15:16)
    at /packages/snippet-injector/lib/snippet.js:279:3)
    at Module.get_Module._compile (/usr/share/atom/resources/app/static/<embedded>:11:146684)
    at Object.value [as .js] (/usr/share/atom/resources/app/static/<embedded>:11:150231)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
```

### Commands

```
```

### Non-Core Packages

```
ask-stack 2.2.0 
atom-autocomplete-php 0.25.6 
Atom-Bash-Snippets 0.0.3 
atom-beautify 0.33.4 
atom-i18n 0.16.3 
atom-ide-ui 0.13.0 
atom-password-generator 0.4.2 
snippet-injector 1.5.4 
atom-wordpress 0.3.0 
autocomplete 0.47.0 
autocomplete-paths 2.12.2 
blade-snippets 0.2.0 
blade-spacer 0.4.2 
copy-path 0.5.1 
cson 2.0.1 
docblockr 0.13.7 
emmet 2.4.3 
file-icons 2.1.27 
file-type-icons 1.3.4 
git-control 0.9.0 
git-log 0.4.1 
git-time-machine 2.1.0 
hide-tree-view-icons 2.0.0 
highlight-selected 0.14.0 
ide-css 0.3.2 
ide-haskell 2.4.0 
ide-html 0.5.0 
ide-json 0.2.1 
ide-php 0.7.17 
ide-python 1.1.0 
ide-vue 0.1.9 
ide-yaml 0.4.4 
jquery-snippets 11.0.0 
language-blade 0.41.4 
language-sql-mysql 0.3.1 
laravel 0.7.1 
laravel-docs 1.0.3 
laravel-eloquent-snippets 2.0.0 
lipsum 0.1.0 
minimap 4.29.9 
minimap-autohide 0.10.1 
minimap-bookmarks 0.4.2 
minimap-cursorline 0.2.0 
minimap-find-and-replace 4.5.2 
minimap-git-diff 4.3.1 
minimap-highlight-selected 4.6.1 
minimap-pigments 0.2.2 
minimap-selection 4.5.0 
nv-dark-syntax 1.4.0 
open-on-bitbucket 0.5.0 
overlay-status-icons 0.1.6 
pigments 0.40.2 
quick-query 1.0.1 
scroll-through-time 0.3.0 
split-diff 1.5.3 
sync-settings 0.8.6 
teletype 0.13.3 
tree-view-copy-relative-path 1.2.0 
tree-view-git-branch 0.1.2 
tree-view-sort 0.11.0 
vertex-ui 0.11.0 
wordpress-api 1.2.2 
```

**Comment by kereborn** [comment]
I needed to install npm, and therefor nodejs, to be able to install cson. It now works,but it seems this package has a nodejs dependency. I didn't really want to install nodejs for this purpose. It it possible for snippet-injector to use the cson package with atom itself?
